from django.core.management.base import BaseCommand
from core.models import Phone

class Command(BaseCommand):
    help = 'Seeds the database with initial phone data'

    def handle(self, *args, **kwargs):
        phones_data = [
          {
            "id": "iphone-15-pro",
            "brand": "Apple",
            "model": "iPhone 15 Pro",
            "description": "Apple's flagship phone with A17 Pro chip, titanium design, and advanced camera system.",
            "image": "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/iPhone%2015%20Pro%20png-tMUZBmwH6Ic3UAcRfwFvZLLuOhzZl3.png",
            "tags": ["New", "Premium"],
            "specs": {
              "display": "6.1-inch Super Retina XDR display with ProMotion",
              "processor": "A17 Pro chip",
              "ram": "8 GB",
              "storage": "256 GB",
              "camera": "48MP main, 12MP ultra wide, 12MP telephoto",
              "battery": "3,274 mAh",
              "os": "iOS 17",
              "display_type": "OLED",
              "display_resolution": "2556 x 1179 pixels",
              "display_ppi": "460 ppi",
              "display_refresh_rate": "120 Hz",
              "display_brightness": "2000 nits (peak)",
              "processor_cores": "6-core",
              "processor_nm": "3 nm",
              "front_camera": "12MP TrueDepth",
              "video_recording": "4K at 60 fps",
              "water_resistance": "IP68",
              "dimensions": "146.6 x 70.6 x 8.25 mm",
              "weight": "187 g",
              "charging": "27W wired, 15W MagSafe",
              "colors": "Natural Titanium, Blue Titanium, White Titanium, Black Titanium",
              "connectivity": "5G, Wi-Fi 6E, Bluetooth 5.3, Ultra Wideband",
              "biometrics": "Face ID",
              "special_features": "Action button, USB-C, Titanium frame",
            },
            "prices": {
              "amazon": 134900,
              "flipkart": 136900,
            },
          },
          {
            "id": "iphone-15",
            "brand": "Apple",
            "model": "iPhone 15",
            "description": "The latest iPhone with A16 Bionic chip, Dynamic Island, and improved camera system.",
            "image": "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/iphone%2015%20black%20png-01w6jRpWONHOHxq3LhQ4KRFuO9QA8K.png",
            "tags": ["New", "Popular"],
            "specs": {
              "display": "6.1-inch Super Retina XDR display",
              "processor": "A16 Bionic chip",
              "ram": "6 GB",
              "storage": "128 GB",
              "camera": "48MP main, 12MP ultra wide",
              "battery": "3,349 mAh",
              "os": "iOS 17",
              "display_type": "OLED",
              "display_resolution": "2556 x 1179 pixels",
              "display_ppi": "460 ppi",
              "display_refresh_rate": "60 Hz",
              "display_brightness": "1600 nits (peak)",
              "processor_cores": "6-core",
              "processor_nm": "4 nm",
              "front_camera": "12MP TrueDepth",
              "video_recording": "4K at 60 fps",
              "water_resistance": "IP68",
              "dimensions": "147.6 x 71.6 x 7.80 mm",
              "weight": "171 g",
              "charging": "20W wired, 15W MagSafe",
              "colors": "Black, Blue, Green, Yellow, Pink",
              "connectivity": "5G, Wi-Fi 6, Bluetooth 5.3, Ultra Wideband",
              "biometrics": "Face ID",
              "special_features": "Dynamic Island, USB-C",
            },
            "prices": {
              "amazon": 79900,
              "flipkart": 77900,
            },
          },
          {
            "id": "samsung-galaxy-s23-ultra",
            "brand": "Samsung",
            "model": "Galaxy S23 Ultra",
            "description": "Samsung's premium smartphone with S Pen support, 200MP camera, and powerful performance.",
            "image": "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Samsung-Galaxy-S24-Ultra-Violet-PNG-fBe6gARky6b0GIN1RvEXI3cQZfrMeL.png",
            "tags": ["Premium", "Camera"],
            "specs": {
              "display": "6.8-inch Dynamic AMOLED 2X display",
              "processor": "Snapdragon 8 Gen 2",
              "ram": "12 GB",
              "storage": "512 GB",
              "camera": "200MP main, 12MP ultra wide, 10MP telephoto",
              "battery": "5,000 mAh",
              "os": "Android 13",
              "display_type": "Dynamic AMOLED 2X",
              "display_resolution": "3088 x 1440 pixels",
              "display_ppi": "500 ppi",
              "display_refresh_rate": "120 Hz",
              "display_brightness": "1750 nits (peak)",
              "processor_cores": "8-core",
              "processor_nm": "4 nm",
              "front_camera": "12MP",
              "video_recording": "8K at 30 fps",
              "water_resistance": "IP68",
              "dimensions": "163.4 x 78.1 x 8.9 mm",
              "weight": "234 g",
              "charging": "45W wired, 15W wireless",
              "colors": "Phantom Black, Cream, Green, Lavender",
              "connectivity": "5G, Wi-Fi 6E, Bluetooth 5.3, Ultra Wideband",
              "biometrics": "Ultrasonic Fingerprint, Face Recognition",
              "special_features": "S Pen included, Samsung DeX, Space Zoom",
            },
            "prices": {
              "amazon": 124999,
              "flipkart": 119999,
            },
          },
          {
            "id": "samsung-galaxy-s23",
            "brand": "Samsung",
            "model": "Galaxy S23",
            "description": "Compact flagship with powerful performance and excellent camera capabilities.",
            "image": "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/samsung%20galaxy%20s24-2qy67xYdScW4lzMa43zzkilH2PcmjR.png",
            "tags": ["Compact", "Performance"],
            "specs": {
              "display": "6.1-inch Dynamic AMOLED 2X display",
              "processor": "Snapdragon 8 Gen 2",
              "ram": "8 GB",
              "storage": "256 GB",
              "camera": "50MP main, 12MP ultra wide, 10MP telephoto",
              "battery": "3,900 mAh",
              "os": "Android 13",
              "display_type": "Dynamic AMOLED 2X",
              "display_resolution": "2340 x 1080 pixels",
              "display_ppi": "425 ppi",
              "display_refresh_rate": "120 Hz",
              "display_brightness": "1750 nits (peak)",
              "processor_cores": "8-core",
              "processor_nm": "4 nm",
              "front_camera": "12MP",
              "video_recording": "8K at 30 fps",
              "water_resistance": "IP68",
              "dimensions": "146.3 x 70.9 x 7.6 mm",
              "weight": "168 g",
              "charging": "25W wired, 15W wireless",
              "colors": "Phantom Black, Cream, Green, Lavender",
              "connectivity": "5G, Wi-Fi 6E, Bluetooth 5.3",
              "biometrics": "Ultrasonic Fingerprint, Face Recognition",
              "special_features": "Samsung DeX, Wireless PowerShare",
            },
            "prices": {
              "amazon": 74999,
              "flipkart": 72999,
            },
          },
          {
            "id": "google-pixel-7-pro",
            "brand": "Google",
            "model": "Pixel 7 Pro",
            "description": "Google's flagship with Tensor G2 chip, excellent camera capabilities, and pure Android experience.",
            "image": "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Google-Pixel-8-Pro-Bay-Custom-Mac-BD-BnaU3dlKyJVjNhw4xMEFohyaPJ9gk5.png",
            "tags": ["Camera", "AI"],
            "specs": {
              "display": "6.7-inch LTPO OLED display",
              "processor": "Google Tensor G2",
              "ram": "12 GB",
              "storage": "256 GB",
              "camera": "50MP main, 12MP ultra wide, 48MP telephoto",
              "battery": "5,000 mAh",
              "os": "Android 13",
              "display_type": "LTPO OLED",
              "display_resolution": "3120 x 1440 pixels",
              "display_ppi": "512 ppi",
              "display_refresh_rate": "120 Hz",
              "display_brightness": "1500 nits (peak)",
              "processor_cores": "8-core",
              "processor_nm": "5 nm",
              "front_camera": "10.8MP",
              "video_recording": "4K at 60 fps",
              "water_resistance": "IP68",
              "dimensions": "162.9 x 76.6 x 8.9 mm",
              "weight": "212 g",
              "charging": "23W wired, 23W wireless",
              "colors": "Obsidian, Snow, Hazel",
              "connectivity": "5G, Wi-Fi 6E, Bluetooth 5.2, Ultra Wideband",
              "biometrics": "In-display Fingerprint, Face Unlock",
              "special_features": "Magic Eraser, Photo Unblur, Google Assistant",
            },
            "prices": {
              "amazon": 69999,
              "flipkart": 67999,
            },
          },
          {
            "id": "google-pixel-7",
            "brand": "Google",
            "model": "Pixel 7",
            "description": "Flagship performance with Google's AI features and excellent camera at a more affordable price.",
            "image": "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/google-pixel-8-l99uZ6tiQ76vCcxLQogUnrAIxAh4G5.png",
            "tags": ["Value", "Camera"],
            "specs": {
              "display": "6.3-inch OLED display",
              "processor": "Google Tensor G2",
              "ram": "8 GB",
              "storage": "128 GB",
              "camera": "50MP main, 12MP ultra wide",
              "battery": "4,355 mAh",
              "os": "Android 13",
              "display_type": "OLED",
              "display_resolution": "2400 x 1080 pixels",
              "display_ppi": "416 ppi",
              "display_refresh_rate": "90 Hz",
              "display_brightness": "1400 nits (peak)",
              "processor_cores": "8-core",
              "processor_nm": "5 nm",
              "front_camera": "10.8MP",
              "video_recording": "4K at 60 fps",
              "water_resistance": "IP68",
              "dimensions": "155.6 x 73.2 x 8.7 mm",
              "weight": "197 g",
              "charging": "20W wired, 20W wireless",
              "colors": "Obsidian, Snow, Lemongrass",
              "connectivity": "5G, Wi-Fi 6E, Bluetooth 5.2",
              "biometrics": "In-display Fingerprint, Face Unlock",
              "special_features": "Magic Eraser, Photo Unblur, Google Assistant",
            },
            "prices": {
              "amazon": 49999,
              "flipkart": 47999,
            },
          },
        ]

        for phone_data in phones_data:
            Phone.objects.update_or_create(
                id=phone_data['id'],
                defaults=phone_data
            )
        
        self.stdout.write(self.style.SUCCESS('Successfully seeded phone data'))
